<a href="https://colab.research.google.com/github/shainaelevado/Linear-Algebra_CHE-2nd-Sem-2022/blob/main/Assignment3_Elevado_Nebres.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Assignment 3: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions

### Objectives
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations
3. Program and translate matrix equations and operations using Python.



# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimentional equations to even hundreds and thousand of them.

Let's say for example you have *A* and *B* as system of equation

$$
A = \left\{
    \begin{array}\
        x + y\\
        4x - 10y
    \end{array}
\right.\\
B = \left\{
    \begin{array}\
      x+y+z \\
      3x -2y -z \\
      -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w- x -2y +z \\
      2w -x + 3y - 2z
    \end{array}
\right. 
$$

We could see that *A* is a system of 2 equations with 2 parameters. while *B* is a system of 3 eqautions with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & -10\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix} $$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the element of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas *A* is a matrix consisting of elements denoted by *aij*. Denoted by *i* is the number of rows in the matrix while *j* stands for the number of columns

$$
A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. since you already know how to describe vectors using **shape, dimensions** and **size** attributes. We'll use them to analyze these matrices

In [ ]:
## Since we'll keep on describing matrices. Let's make a function

def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Delcaring a 2 x 2 matrix

A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

In [ ]:
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

In [ ]:
H = np.array([1,2,3,4])
describe_mat(H)

Matrix:
[1 2 3 4]

Shape: (4,)
Rank: 1

## Categorizing Matrices

There are several ways of classifying matrices. Once coulb be according to their **shape** and another is according to their **element values**. We'll try to go through them.

### Row and Column Matrices

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

In [ ]:
col_mat = np.array([
    [2],
    [6],
    [10]
]) ## this is a 2-D Matrix with a shape of (3,2)
describe_mat(col_mat)


### Square Matrices

Square matrices have have the same row and column sizes. We could say a mtrix square if *i = j*. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,7,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,6],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

In [2]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [3]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


## Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


## Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])


In [ ]:
d = np.diag([2,3,5,7])
#d.shape[0] == d.shape[1]
d

## Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [4]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [5]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal

In [ ]:
np.array([
    [1,2,3,5],
    [0,3,1,-2],
    [0,0,5,3],
    [0,0,0,3]
])


In [ ]:
F = np.array([
              [1, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [-2, -3, 5, -5, 6],
              [-6, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)

## Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal

In [ ]:
np.tril(F)

## Practice
Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H


In [ ]:
def create_user (userid):
    print("Successfully created user: {}".format(userid))

userid = 2021_100001
create_user(2021-100100)

## Matrix Algebra

### Addition

In [7]:
A = np.array([
    [1,2],
    [2,3],
    [4,1],          
])
B = np.array([
     [2,2],
     [0,0],
     [1,1],       
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [8]:
3+A ##Broadcasting
# 2*np;.ones(A.shape)+A

array([[4, 5],
       [5, 6],
       [7, 4]])

### Subtraction

In [9]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [11]:
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

### Element-wise Multiplication

In [12]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [13]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

## Task 1

Create a function named mat_desc() that thoroughly describes a matrix, it should:
1. Displays the shape, size and rank of the matrix
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix.


Use 3 sample matrices in which their shapes are not lower than (3,3), In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared. 

In [14]:
## Function Area

import numpy as np

In [15]:
## Matrix Declarations

def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [16]:
## Sample Matrices

print('Matrix 1:')
mat_desc([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print('Matrix 2:')
mat_desc([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
print('Matrix 3:')
mat_desc([[1, 2, 3], [4, 5, 6], [5, 6, 8]])

Matrix 1:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 2:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 3:
[[1 2 3]
 [4 5 6]
 [5 6 8]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


## Task 2

Create a function named mat_operations() that takes in two matrices a inpyt marameters it should:
1. Determines if the matrices are viable for operation and returns your own error mesage if they are not viable.
2. Returns the sum of the matrices.
3. Returns the difference of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower thant (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [17]:

import numpy as np

In [18]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The shape of both matrices are not same. Could not perform operations.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the given matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-wise division of the given matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [25]:
print('Sample 1:')
mat_operations([[1, 0, 0], [0, 1, 0], [0, 0, 1]], [[1, 2, 4], [2, 3, 4], [4, 5, 6]])
print('Sample 2:')
mat_operations([[2, 0, 0], [0, 2, 0], [0, 0, 2]], [[1, 2, 4], [2, 3, 4], [4, 5, 6]])
print('Sample 3:')
mat_operations([[1, 2, 3], [4, 5, 6], [5, 6, 8]], [[1, 2, 4], [2, 3, 4], [4, 5, 6]])

Sample 1:
Matrix 1: [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix 2: [[1 2 4]
 [2 3 4]
 [4 5 6]]
Sum of the given matrices:
[[2 2 4]
 [2 4 4]
 [4 5 7]]
Difference of the given matrices:
[[ 0 -2 -4]
 [-2 -2 -4]
 [-4 -5 -5]]
Element-wise multiplication of the given matrices:
[[1 0 0]
 [0 3 0]
 [0 0 6]]
Element-wise division of the given matrices:
[[1.         0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.16666667]]
Sample 2:
Matrix 1: [[2 0 0]
 [0 2 0]
 [0 0 2]]
Matrix 2: [[1 2 4]
 [2 3 4]
 [4 5 6]]
Sum of the given matrices:
[[3 2 4]
 [2 5 4]
 [4 5 8]]
Difference of the given matrices:
[[ 1 -2 -4]
 [-2 -1 -4]
 [-4 -5 -4]]
Element-wise multiplication of the given matrices:
[[ 2  0  0]
 [ 0  6  0]
 [ 0  0 12]]
Element-wise division of the given matrices:
[[2.         0.         0.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.33333333]]
Sample 3:
Matrix 1: [[1 2 3]
 [4 5 6]
 [5 6 8]]
Matrix 2: [[1 2 4]
 [2 3 4]
 [4 5 6]]
Sum of the give